### PR TITLE
[DRAFT] adding claude support for llmclassifier

### PR DESCRIPTION
**Pull request by dheerajiiitv**
Changes:
* Addition support for claude for LLMClassifier

### CODE REVIEW

**Comment by dheerajiiitv** [comment]
@ankrgyl Please take a look, am I going into the right direction.
Please suggest any changes

**Comment by ankrgyl** [comment]
Hey @dheerajiiitv!

Claude actually works out of the box now, because we (a) added support for it in our proxy, (b) autoevals uses the proxy by default, and (c) claude3 now supports tool calling!!

There is a bug in Claude where it doesn't support arrays of strings in the tool calls, so I think to enable it, we just need to:

* Try swapping in `claude-3-haiku-20240307` as the model
  * You shoould see it break/complain about not being able to parse the response
* Try changing the type of reasons in the JSON schema to be a string instead of an array of strings

I think we can either then special case that (so it's a string vs. an array of strings for `reason`), or do that always, including for OpenAI.

**Comment by dheerajiiitv** [comment]
this is not useful at all than 😞 ?

**Comment by ankrgyl** [comment]
I think the outcome is useful! But ideally we can solve for it without introducing a new dependency and set of code that we need to support for all future evaluators/models. Really appreciate the contribution either way.

**Comment by dheerajiiitv** [comment]
We want to make it more generic for flexibility for future evaluators right?

**Comment by ankrgyl** [comment]
Could you give me an example?

**Comment by dheerajiiitv** [comment]
Sorry Missed it,
Just want to clarify few things:
> Claude actually works out of the box now, because we (a) added support for it in our proxy, (b) autoevals uses the proxy by default, and (c) claude3 now supports tool calling!!

Yes, If we already support claude function calling, How can we use LLMClassifier with Claude?

> There is a bug in Claude where it doesn't support arrays of strings in the tool calls, so I think to enable it, we just need to:
I tried with opus and the sonnet model function calling was working fine. I'll check for haiku model and fix the bug.


> I think the outcome is useful! But ideally we can solve for it without introducing a new dependency and set of code that we need to support for all future evaluators/models. Really appreciate the contribution either way.
>> We want to make it more generic for flexibility for future evaluators right?

From based on the conversation we had, I understand we want to support other LLMs with OpenAI not just claude so you want to structure code in such a way that we can easily extend our model support in future. 
```

llm_wrapper/
    base_wrapper.py
    oai.py
    claude.py
    vertexai.py
    ..

```

```
base_llm.py
openai_llm.py
claude_llm.py

```


Something like above?

**Comment by ankrgyl** [comment]
> Yes, If we already support claude function calling, How can we use LLMClassifier with Claude?

Per my comment above, it _almost_ works. You can just specify a claude model of your choice as the `model` argument, and since it goes through the Braintrust proxy, it'll work. The only issue is that Claude does not support arrays in function calls properly, so we need to fix that.

> From based on the conversation we had, I understand we want to support other LLMs with OpenAI not just claude so you want to structure code in such a way that we can easily extend our model support in future.

Yes, we'd like to do this through the [proxy](https://www.braintrustdata.com/docs/guides/proxy), which autoevals is already configured to call. That allows us to avoid proliferating multiple model implementations here, and instead, solve for cross-model compatibility issues in one place.

**Comment by dheerajiiitv** [comment]
@ankrgyl Let me check it out. Let me find a solution

**Pull request closed without merging**
